### ISSUE TITLE
auto-sync timing doesn't seem to take

### ISSUE THREAD

**Issue by cori** [mlava/quick-capture#2]
I've been troubleshooting an issue I _think_ i'm seeing with Todoists with comments, and I decreased the autosync time to two minutes, but the extension is still checking every 15.

I tried to capture screenshots to illustrate - the first is my config, the second is the waterfall of the `tasks` requests with the timing show - you can see these hit every 15 minutes or so,

<img width="660" alt="image" src="https://user-images.githubusercontent.com/46317/210177380-f792d821-0e00-4a4f-850e-427862b3613d.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/46317/210177497-926d44ce-c4a9-4cd0-9a22-088c1fc0643c.png">

**Comment by cori** [comment]
After a couple of days I can no longer repro this - this morning the auto download seems to be firing every two minutes so some combination of enabling / disabling the extension and maybe elapsed time between Roam sessions appears to have synced this up. Closing in the absence of a repro.

**Comment by mlava** [comment]
ok, let me know if it happens again
