### ISSUE TITLE
Todoist notess with comments do not bring comments and hang the import

### ISSUE THREAD

**Issue by cori** [mlava/quick-capture#3]
I had a list of "tasks" in my Todoist Inbox - some with comments and others without.

The ones with comments seem to import the top-line, but then fail when getting the comments and hang the process meaning that subsequent notes also aren't imported.

Here's the content of a corresponding console error

```
710c6a13-bbb0-42fd-afb4-d317fb69ac22:393 Uncaught (in promise) TypeError: Cannot read property 'file_type' of null
    at importTodoist (710c6a13-bbb0-42fd-afb4-d317fb69ac22:393)
    at /async blob:https:/roamresearch.com/710c6a13-bbb0-42fd-afb4-d317fb69ac22:477
importTodoist @ 710c6a13-bbb0-42fd-afb4-d317fb69ac22:393
async function (async)
(anonymous) @ 710c6a13-bbb0-42fd-afb4-d317fb69ac22:477
sentryWrapped @ helpers.ts:98
fetch.ts:35 POST https://o211282.ingest.sentry.io/api/1336449/envelope/?sentry_key=aa087e7956c7463fa87a82953bd1c382&sentry_version=7&sentry_client=sentry.javascript.browser%2F7.28.1 429
(anonymous) @ fetch.ts:35
(anonymous) @ base.ts:75
add @ promisebuffer.ts:49
send @ base.ts:90
t.ut @ baseclient.ts:739
t.sendEvent @ baseclient.ts:304
n.sendEvent @ client.ts:100
(anonymous) @ baseclient.ts:697
(anonymous) @ syncpromise.ts:79
(anonymous) @ syncpromise.ts:183
p @ syncpromise.ts:176
(anonymous) @ syncpromise.ts:97
t @ syncpromise.ts:58
t.then @ syncpromise.ts:69
t.ht @ baseclient.ts:665
t.it @ baseclient.ts:591
t.captureEvent @ baseclient.ts:185
(anonymous) @ hub.ts:241
t.W @ hub.ts:475
t.captureEvent @ hub.ts:240
yr @ globalhandlers.ts:248
(anonymous) @ globalhandlers.ts:149
ot @ instrument.ts:96
tt.onunhandledrejection @ instrument.ts:612
```

**Comment by cori** [comment]
I have 7 "notes", two with comments. The first two imported fine and the third - the first with a comment - hung things. I removed the comment, and on the next run got that task and the subsequent ones until it ran into another with a comment, which hung it.

Also of note (but probably obvious in context) the extension keeps retrying the hung notes, creating new Roam nodes every run.

**Comment by cori** [comment]
Ok I _think_ what was going on here is that the Drafts Action I was using to populate Todoist created the draft "body" as a comment and not in the description of the task. It still seems possibly problematic that it crashes in this fashion, but I might be doing something else wrong, and switching to a different action put the body in the description and that seems to be working fine.

**Comment by cori** [comment]
I'm going to leave this closed for now - I'll reopen it if I find time to dig into it and maybe supply a PR, but I am still seeing this behavior even sending Drafts to Todoist with a description instead of comments.

Currently I'm sending over a few lines of content in the Draft, including some weather and location info as well as selected text and url from a shared safari page. Sometimes (often?) those show up in Todoist with some sort of attachment and others I send over from Drafts do not have an attachment e.g.

![28338AFA-4CFE-4624-A792-904CED0E3EA6](https://user-images.githubusercontent.com/46317/210237572-e9cd1d57-857b-48e6-9b09-e99ee96cc1d2.jpeg)

the ones without a paper clip come over just fine, but the ones with paper lips get pulled into Roam but don't get marked as pulled so the extension tries again (and again, and again, until I move the task out of my Todoist Inbox). I suspect what's happening (without more than a cursory review of the code) is that the exception that's being throw about the "attachment" prevents the extension from updating its state.

**Comment by mlava** [comment]
I'll take a look over the attachment handling to try to figure out what's going on. Do you have Todoist Free or Premium?

**Comment by cori** [comment]
I'm using Free.

I've seen some other ... oddities around parent blocks and block uids so I sorta figured I might be stressing things out by making a lot of changes to the config so I haven't opened issues for those.

**Comment by mlava** [comment]
@cori 
Thanks for reporting this. I have now fixed this in https://github.com/Roam-Research/roam-depot/pull/481
Cheers!
