### ISSUE TITLE
[Feature Request] Option to replace underscore with space when importing labels

### ISSUE THREAD

**Issue by msf999** [mlava/quick-capture#4]
Thank you for the extension, it makes capturing things into Roam much easier. I am wondering if it is possible to add an option to replace underscore with space when importing labels? Todoist doesn't allow spaces in labels and some of my Roam tags have spaces in them. 

Thanks :)

**Comment by mlava** [comment]
Thanks for the suggestion. Will look into a fix!

**Comment by mlava** [comment]
This is now implemented - there is a switch in settings to turn it on. You will need to wait for the RR team to review the update and approve before you see it. Thanks for the useful suggestion!

https://github.com/Roam-Research/roam-depot/pull/465
